INSERT INTO ROLE (ID,CODE) VALUES (1,'ROLE_ADMIN');

INSERT INTO USER (ID,PASSWORD,USER_CODE) VALUES (1,'$2a$10$DKIJPQA7cAlnk93UOfnhienddoqokKEmurmUSmZrSqoyDzka.HFIK','alonso');

INSERT INTO USER_ROLE (USER,ROLE) VALUES (1,1);